### ISSUE TITLE
Items not stacking correctly

### ISSUE THREAD

**Issue by Parksinjunn** [SharkieTV/BetterMinecraft#2]
Good day, I know this has been mentioned a few times in the discord, but there is an issue with item stacking (at least in BetterMinecraft [plus]. It seems like the NBT data is being messed up somehow. One way that I've found to be 100% effective in recreating the issue is shearing a sheep. Any wool picked up in a chest or picked up in the overworld elsewhere (through breaking it or whatnot) stacks together separately from any wool that is sheared off a sheep. I've noticed similar stacking issues with seeds and some random stacking glitches with blocks. Not sure what could be causing this, once they are dropped on the ground, they stack together, and then once picked up complete a full-stack. While this isn't an extreme issue, it is annoying nonetheless and makes storing things in chests more of a tedious chore than it already is. Below I've included a gif of the issue occurring: https://imgur.com/a/CGNPjgL

**Comment by NateSkii** [comment]
Im having the same issue

**Comment by SharkieTV** [comment]
we are aware of this issue and tying to fix it
